#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except ports 22, 80, and 443
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
EOF
