#!/usr/bin/env bash
# Fixes Nginx to listen on port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
service nginx restart
EOF
